development:
  adapter: postgresql
  database: cutnedge_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cutnedge_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cutnedge_production
  pool: 5
  timeout: 5000
